version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-serverless-workflow-manager"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cu9oyxmbebq7"
s3_prefix = "aws-serverless-workflow-manager"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
tags = "project=\"aws-serverless-workflow-manager\" stage=\"production\""
