app: serverless-workflow-manager
service: serverless-workflow-manager-v2
provider:
  name: aws
  region: ap-south-1
  runtime: python3.7
  lambdaHashingVersion: '20201221'
  stage: dev
functions:
  producer:
    handler: process_sqs_event.lambda_handler
    events:
      - sqs: arn:aws:sqs:ap-south-1:584566845197:workflow_queue
plugins:
  - serverless-lift
