version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
  serverless: circleci/serverless-framework@1.0.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/simple-serverless-rule-engine
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run pytest
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
          app-name: serverless-framework-orb
          org-name: circleci
      - run:
          command: serverless deploy -v
          name: deploy
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy